# Generated by Django 4.2.6 on 2023-10-25 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('contract_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Nro. De Contrato')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_1', models.CharField(max_length=20, verbose_name='Teléfono 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 2')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('customer_type', models.CharField(choices=[('FR', 'Fibra Residencial'), ('FP', 'Fibra PYME'), ('OT', 'Otro')], default='FR', max_length=2, verbose_name='Tipo De Cliente')),
                ('plan', models.CharField(choices=[('BA', 'Básico'), ('BP', 'Básico Plus'), ('BR', 'Bronce'), ('PL', 'Plata'), ('OR', 'Oro'), ('EM', 'Emprendedor'), ('PR', 'Productivo'), ('PP', 'Productivo Pro'), ('VP', 'Visionario Pro'), ('OT', 'Otro')], default='BR', max_length=2, verbose_name='PLAN')),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Asignado a')),
                ('seller', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendedor')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observaciones')),
                ('date_assigned', models.DateField(blank=True, null=True, verbose_name='Fecha Recibida')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha De Creación')),
                ('date_udpated', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField(blank=True, null=True, verbose_name='Zona')),
                ('olt', models.IntegerField(blank=True, null=True, verbose_name='OLT')),
                ('pon', models.IntegerField(blank=True, null=True, verbose_name='PON')),
                ('card', models.IntegerField(blank=True, null=True, verbose_name='Tarjeta')),
                ('box', models.IntegerField(blank=True, null=True, verbose_name='Caja')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Puerto')),
                ('box_power', models.FloatField(blank=True, null=True, verbose_name='Potencia Caja')),
                ('house_power', models.FloatField(blank=True, null=True, verbose_name='Potencia Roseta')),
                ('onu_serial', models.CharField(blank=True, max_length=32, null=True, verbose_name='Serial ONU')),
                ('router_serial', models.CharField(blank=True, max_length=32, null=True, verbose_name='Serial ONU')),
                ('drop_serial', models.IntegerField(blank=True, null=True, verbose_name='Serial DROP')),
                ('drop_used', models.IntegerField(blank=True, null=True, verbose_name='DROP')),
                ('hook_used', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tensores')),
                ('fast_conn_used', models.IntegerField(blank=True, default=2, null=True, verbose_name='Conectores')),
                ('extra_comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Información')),
            ],
            options={
                'verbose_name': 'installation',
                'verbose_name_plural': 'installations',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('document_id', models.IntegerField(verbose_name='Nro. De Cédula')),
                ('phone_1', models.CharField(max_length=20, verbose_name='Teléfono 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 2')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('rol', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol')),
                ('has_vehicle', models.BooleanField(verbose_name='¿Posee vehículo?')),
                ('vehicle_data', models.CharField(blank=True, max_length=100, null=True, verbose_name='Datos del vehículo')),
            ],
            options={
                'verbose_name': 'technician',
                'verbose_name_plural': 'technicians',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('INS', 'Instalación'), ('MIG', 'Migración'), ('MUD', 'Mudanza'), ('M&M', 'Migración y mudanza'), ('SER', 'Servicio'), ('OTR', 'Otro')], default='INS', max_length=3, verbose_name='Categoría')),
                ('completed', models.BooleanField(verbose_name='Completada')),
                ('extra_order_comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Información extra')),
                ('closed', models.BooleanField(verbose_name='Orden Cerrada')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_control.customer', verbose_name='Cliente')),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order_control.installation', verbose_name='Instalación')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_control.technician', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
