# Generated by Django 4.2.6 on 2023-10-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('INS', 'Instalación'), ('MIG', 'Migración'), ('MUD', 'Mudanza'), ('M&M', 'Migración y mudanza'), ('SER', 'Servicio'), ('OTR', 'Otro')], default='INS', max_length=3, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='order',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Orden Cerrada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_control.installation', verbose_name='Instalación'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='has_vehicle',
            field=models.BooleanField(default=False, verbose_name='¿Posee vehículo?'),
        ),
    ]
