# Generated by Django 4.2.6 on 2023-10-26 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0002_remove_order_category_customer_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha De Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_udpated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
    ]
