# Generated by Django 4.2.6 on 2023-10-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0003_order_date_created_order_date_udpated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_udpated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_udpated',
            new_name='date_updated',
        ),
    ]
