# Generated by Django 4.2.6 on 2023-10-29 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0004_rename_date_udpated_customer_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='installation',
        ),
        migrations.AddField(
            model_name='installation',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_control.order', verbose_name='Orden de instalación'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.CharField(choices=[('BA', 'Básico'), ('BP', 'Básico Plus'), ('BR', 'Bronce'), ('PL', 'Plata'), ('OR', 'Oro'), ('EM', 'Emprendedor'), ('PR', 'Productivo'), ('PP', 'Productivo Pro'), ('VP', 'Visionario Pro'), ('OT', 'Otro')], default='BR', max_length=2, verbose_name='Plan'),
        ),
    ]
