# Generated by Django 4.2.6 on 2023-10-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0005_remove_order_installation_installation_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Asignada para'),
        ),
    ]
