# Generated by Django 4.2.6 on 2023-11-12 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0006_order_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='router_serial',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Serial Router'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha a realizar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_technician', to='order_control.technician', verbose_name='Técnico'),
        ),
    ]
