# Generated by Django 4.2.6 on 2023-11-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0008_alter_order_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='order', to='order_control.technician', verbose_name='Técnico'),
        ),
    ]
