# Generated by Django 4.2.6 on 2023-11-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0009_alter_order_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation', to='order_control.order', verbose_name='Orden de instalación'),
        ),
    ]
