# Generated by Django 5.1.5 on 2025-01-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
