# Generated by Django 5.1.5 on 2025-01-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_customer_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='address',
            field=models.TextField(verbose_name='Dirección'),
        ),
    ]
