# Generated by Django 5.1.5 on 2025-01-21 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_technician_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstallation',
            name='drop_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Metraje DROP'),
        ),
        migrations.AlterField(
            model_name='historicalinstallation',
            name='num_connectors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de conectores'),
        ),
        migrations.AlterField(
            model_name='historicalinstallation',
            name='num_tensioners',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de tensores'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.drop', verbose_name='Serial DROP'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='drop_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Metraje DROP'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='num_connectors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de conectores'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='num_tensioners',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de tensores'),
        ),
    ]
