# Generated by Django 5.1.5 on 2025-01-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_historicalinstallation_drop_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'municipality',
                'verbose_name_plural': 'municipalities',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.municipality', verbose_name=''),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='municipality',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.municipality', verbose_name=''),
        ),
    ]
