# Generated by Django 5.1.5 on 2025-01-23 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_municipality_customer_municipality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installationcategory',
            old_name='installaion_category',
            new_name='installation_category',
        ),
        migrations.AlterField(
            model_name='customer',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.municipality', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='municipality',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.municipality', verbose_name='Municipio'),
        ),
    ]
