# Generated by Django 5.1.5 on 2025-01-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_historicalinstallation_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstallation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='status',
        ),
        migrations.DeleteModel(
            name='InstallationStatus',
        ),
    ]
